esphome:
  name: boiler-room-gas-sun
  friendly_name: Boiler room - Gas and Sun panels

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_gas_sun

ota:
  - platform: esphome
    password: !secret ota_password_gas_sun

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.112
    gateway: 192.168.1.1
    subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Boiler-Room-Gas-Sun"
    password: !secret ap_password_gas_sun

captive_portal:



# [12:44:29.538][C][gpio.one_wire:086]:     0x29000003ea397228 (DS18B20) Tepla voda solar
# [12:44:29.539][C][gpio.one_wire:086]:     0xe1000003ea1cbe28 (DS18B20) Vrat solar
# [14:09:41.608][C][gpio.one_wire:086]:     0xf70000006cd75d28 (DS18B20) Teplota uzitkove vody (za smesovacem)

one_wire:
  - platform: gpio
    pin: GPIO2

sensor:
  - platform: dallas_temp
    address: 0x29000003ea397228
    name: Teplota - Solar vstup (tepla voda)
    update_interval: 30s
  - platform: dallas_temp
    address: 0xe1000003ea1cbe28
    name: Teplota - Solar> vrat
    update_interval: 30s
  - platform: dallas_temp
    address: 0xf70000006cd75d28
    name: Teplota - Uzitkova voda - za smesovacem
    update_interval: 15s
  # - platform: dallas_temp
  #   address: 0x60000003ea354528 # Jeste neurceno
  #   name: Teplota - Kotel> vrat
  #   update_interval: 30s  
  # - platform: dallas_temp
  #   address: 0xb800000559ebf028
  #   name: Teplota - Test
  #   update_interval: 30s  
     

output:
  - platform: gpio
    pin: GPIO15
    id: gpio_rele
  - platform: gpio
    pin: GPIO0
    id: gpio_led_yellow
  - platform: gpio
    pin: GPIO5
    id: gpio_led_red
  - platform: gpio
    pin: GPIO4
    id: gpio_led_green
    
switch:
  - platform: output
    name: LED Yellow
    output: gpio_led_yellow
    id: switch_led_yellow
    internal: True
  - platform: output
    name: LED Red
    output: gpio_led_red
    id: switch_led_red
    internal: True
  - platform: output
    name: LED Green
    output: gpio_led_green
    id: switch_led_green
    internal: True
  - platform: output
    name: Rele
    output: gpio_rele
    id: switch_rele
    # When this switch changes, update the target switch
    on_state:
      - switch.control:
          id: switch_led_yellow
          state: !lambda "return x;"

binary_sensor:
  - platform: switch
    name: "Status - Green"
    source_id: switch_led_green  # References the id of the switch above
  - platform: switch
    name: "Status - Yellow"
    source_id: switch_led_yellow  # References the id of the switch above
  - platform: switch
    name: "Status - Red"
    source_id: switch_led_red  # References the id of the switch above

interval:
  - interval: 1s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - if:
              condition:
                api.connected:
              then:
                - switch.turn_on: switch_led_green
                - switch.turn_off: switch_led_red
              else:
                - switch.turn_off: switch_led_red
                - switch.turn_on: switch_led_green
                - delay: 500ms
                - switch.turn_off: switch_led_green
                - delay: 500ms
        else:
          - switch.turn_off: switch_led_green
          - switch.turn_on: switch_led_red
          - delay: 500ms
          - switch.turn_off: switch_led_red
          - delay: 500ms
    